package com.chervon.iot.mobile.model;

import java.io.Serializable;

public class MsgTable implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgtable.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgtable.finalstatus
     *
     * @mbggenerated
     */
    private String finalstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgtable.msgtype
     *
     * @mbggenerated
     */
    private String msgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgtable.json
     *
     * @mbggenerated
     */
    private Object json;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgtable.recalltimes
     *
     * @mbggenerated
     */
    private Integer recalltimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msgtable.recallstatus
     *
     * @mbggenerated
     */
    private Boolean recallstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgtable.id
     *
     * @return the value of msgtable.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgtable.id
     *
     * @param id the value for msgtable.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgtable.finalstatus
     *
     * @return the value of msgtable.finalstatus
     *
     * @mbggenerated
     */
    public String getFinalstatus() {
        return finalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgtable.finalstatus
     *
     * @param finalstatus the value for msgtable.finalstatus
     *
     * @mbggenerated
     */
    public void setFinalstatus(String finalstatus) {
        this.finalstatus = finalstatus == null ? null : finalstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgtable.msgtype
     *
     * @return the value of msgtable.msgtype
     *
     * @mbggenerated
     */
    public String getMsgtype() {
        return msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgtable.msgtype
     *
     * @param msgtype the value for msgtable.msgtype
     *
     * @mbggenerated
     */
    public void setMsgtype(String msgtype) {
        this.msgtype = msgtype == null ? null : msgtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgtable.json
     *
     * @return the value of msgtable.json
     *
     * @mbggenerated
     */
    public Object getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgtable.json
     *
     * @param json the value for msgtable.json
     *
     * @mbggenerated
     */
    public void setJson(Object json) {
        this.json = json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgtable.recalltimes
     *
     * @return the value of msgtable.recalltimes
     *
     * @mbggenerated
     */
    public Integer getRecalltimes() {
        return recalltimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgtable.recalltimes
     *
     * @param recalltimes the value for msgtable.recalltimes
     *
     * @mbggenerated
     */
    public void setRecalltimes(Integer recalltimes) {
        this.recalltimes = recalltimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msgtable.recallstatus
     *
     * @return the value of msgtable.recallstatus
     *
     * @mbggenerated
     */
    public Boolean getRecallstatus() {
        return recallstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msgtable.recallstatus
     *
     * @param recallstatus the value for msgtable.recallstatus
     *
     * @mbggenerated
     */
    public void setRecallstatus(Boolean recallstatus) {
        this.recallstatus = recallstatus;
    }
}