package com.chervon.iot.ablecloud.mapper;

import com.chervon.iot.ablecloud.model.Able_Device;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface Able_DeviceMapper {
    /**
     * 根据username查询device id集合
     * @param userSfid
     * @return
     */
    List<Able_Device> selectDevicesByUserSfid(String userSfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table able_device
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table able_device
     *
     * @mbggenerated
     */
    int insert(Able_Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table able_device
     *
     * @mbggenerated
     */
    int insertSelective(Able_Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table able_device
     *
     * @mbggenerated
     */
    Able_Device selectByPrimaryKey(String deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table able_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Able_Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table able_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Able_Device record);

    Able_Device selectByDeviceUserSfId(String usersfid, String device_id);
}