package com.chervon.iot.ablecloud.model;

import org.springframework.stereotype.Component;

@Component
public class Able_Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column able_device.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column able_device.product_code
     *
     * @mbggenerated
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column able_device.usersfid
     *
     * @mbggenerated
     */
    private String usersfid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column able_device.isdelete
     *
     * @mbggenerated
     */
    private Boolean isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column able_device.user_can_control
     *
     * @mbggenerated
     */
    private Boolean userCanControl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column able_device.last_modified
     *
     * @mbggenerated
     */
    private String lastModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column able_device.device_id
     *
     * @return the value of able_device.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column able_device.device_id
     *
     * @param deviceId the value for able_device.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column able_device.product_code
     *
     * @return the value of able_device.product_code
     *
     * @mbggenerated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column able_device.product_code
     *
     * @param productCode the value for able_device.product_code
     *
     * @mbggenerated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column able_device.usersfid
     *
     * @return the value of able_device.usersfid
     *
     * @mbggenerated
     */
    public String getUsersfid() {
        return usersfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column able_device.usersfid
     *
     * @param usersfid the value for able_device.usersfid
     *
     * @mbggenerated
     */
    public void setUsersfid(String usersfid) {
        this.usersfid = usersfid == null ? null : usersfid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column able_device.isdelete
     *
     * @return the value of able_device.isdelete
     *
     * @mbggenerated
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column able_device.isdelete
     *
     * @param isdelete the value for able_device.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column able_device.user_can_control
     *
     * @return the value of able_device.user_can_control
     *
     * @mbggenerated
     */
    public Boolean getUserCanControl() {
        return userCanControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column able_device.user_can_control
     *
     * @param userCanControl the value for able_device.user_can_control
     *
     * @mbggenerated
     */
    public void setUserCanControl(Boolean userCanControl) {
        this.userCanControl = userCanControl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column able_device.last_modified
     *
     * @return the value of able_device.last_modified
     *
     * @mbggenerated
     */
    public String getLastModified() {
        return lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column able_device.last_modified
     *
     * @param lastModified the value for able_device.last_modified
     *
     * @mbggenerated
     */
    public void setLastModified(String lastModified) {
        this.lastModified = lastModified == null ? null : lastModified.trim();
    }
}