package com.chervon.iot.ablecloud.model;

public class Able_Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column able_device.device_id
     *
     * @mbggenerated
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column able_device.product_code
     *
     * @mbggenerated
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column able_device.userSfid
     *
     * @mbggenerated
     */
    private String userSfid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column able_device.isdelete
     *
     * @mbggenerated
     */
    private String isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column able_device.device_id
     *
     * @return the value of able_device.device_id
     *
     * @mbggenerated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column able_device.device_id
     *
     * @param deviceId the value for able_device.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column able_device.product_code
     *
     * @return the value of able_device.product_code
     *
     * @mbggenerated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column able_device.product_code
     *
     * @param productCode the value for able_device.product_code
     *
     * @mbggenerated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column able_device.userSfid
     *
     * @return the value of able_device.userSfid
     *
     * @mbggenerated
     */
    public String getUserSfid() {
        return userSfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column able_device.userSfid
     *
     * @param userSfid the value for able_device.userSfid
     *
     * @mbggenerated
     */
    public void setUserSfid(String userSfid) {
        this.userSfid = userSfid == null ? null : userSfid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column able_device.isdelete
     *
     * @return the value of able_device.isdelete
     *
     * @mbggenerated
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column able_device.isdelete
     *
     * @param isdelete the value for able_device.isdelete
     *
     * @mbggenerated
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }
}