package com.chervon.iot.mobile.mapper;

import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PriorityMapper {
    /**
     * 查询msg类型，并按照优先级code排序
     * @return
     */
    List<String> selectMsgType();

    /**
     * 根据优先级查询msgtype
     * @param code
     * @return
     */
    List<String> selectByCode(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priority
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priority
     *
     * @mbggenerated
     */
    int insert(MsgTableMapper.Priority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priority
     *
     * @mbggenerated
     */
    int insertSelective(MsgTableMapper.Priority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priority
     *
     * @mbggenerated
     */
    MsgTableMapper.Priority selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priority
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MsgTableMapper.Priority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table priority
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MsgTableMapper.Priority record);
}